### PR TITLE
Fix licensing issues

### PR DESCRIPTION
**Pull request by kennytv**
I noticed a small mistake when looking through your source code; the license is wrong! Unless I am mistaken, you are using the [GPLv3 licensed Bukkit library](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/LICENCE.txt), so here you go, fixed that for you! :)

### CODE REVIEW

**Review by NoahvdAa — APPROVED** [review]

**Comment by TechnicallyCoded** [comment]
Using an API does not require you to publish under the same license as that API. If this were a fork of the bukkit library then yes.

**Comment by kennytv** [comment]
I don't think you understand software licenses then; you should read up on the GPL and what the difference to the LGPL is (Wikipedia is good enough for both). Even the mildly protective MIT license includes *use* of the linked code

**Comment by TechnicallyCoded** [comment]
I would appreciate if people would actually contribute useful things. If anything *using* a GPL licensed API had to also be licensed under gpl, nvidia would not be allowed to make closed source drivers for the linux kernel. Given how big of a lawyer team nvidia has. It's safe to say that they know what they are doing. As I have said in the past to other people. I will plainly make the source no longer available if that's what is required for this harassment to stop.

**Comment by kennytv** [comment]
That's not how that works, at all. See https://github.com/torvalds/linux/blob/master/Documentation/process/license-rules.rst for the Linux Kernel licensing, including a "linking exception". All you have to do to understand GPL is to search for its terms on other sites if you don't feel like reading the actual and full legal text.

In any case, it doesn't *actually* matter as noone is going to sue you over it, but it does mean *everyone* can use your code to their heart's content under the terms of the GPL and that the license you currently have is very much invalid

**Comment by TechnicallyCoded** [comment]
Please go after people making money from stolen code that is licensed under something like GPL. This is a FREE, open source, highly optimized plugin that anyone can use to learn. Come back to annoy me once I am charging money for a "highly-optimized version of spigot/paper". I can tell you for a fact those violate all sorts of licenses. I do not feel like giving up my copyright while I am still developing this plugin and that's my choice because it's my code, not yours, and not bukkit's. The project this was forked from is licensed under MIT, which allows sub-licensing btw. It's not a protective license but rather a permissive license.

**Pull request closed without merging**
