### PR TITLE
Add Folia support;

### PR DESCRIPTION
**Pull request by HarvelsX**

### CODE REVIEW

**Comment by TechnicallyCoded** [comment]
I feel like we are reinventing the wheel too much here. I already maintain FoliaLib and what is being done here is basically adding the library into the code base which means I have to keep this integrated lib up to date as well as the other project. 

Additionally, IRP in it's current state was never designed with multiple regions in mind making the Folia adaptation even more messy than original optimizations of moving things off the main thread. I was planning a re-write for this very reason but we all know how ambitious we become with our time.. and 2 months later, I barely started.

FoliaLib even has a version which support legacy-compatible bukkit plugins such as this one:
https://github.com/TechnicallyCoded/FoliaLib/tree/feature/legacy-support

**Comment by HarvelsX** [comment]
Oh, @TechnicallyCoded , you're right! But I would not want to include another library in dependencies, which needs to be included in the jar. I think it would be worth making a PR in **PaperLib** which would adapt the schedulers.

**Comment by TechnicallyCoded** [comment]
Will do this correctly when I have time. Sorry, but closing :/

**Comment by HarvelsX** [comment]
@TechnicallyCoded, np!

**Pull request closed without merging**
